apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          containers:
          - name: hello
            image: curlimages/curl:7.70.0
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - 'curl
              -H "Content-Type: application/json"
              http://172.17.0.7:4000/users'
          restartPolicy: OnFailure
